# 这是一个帮助您开始使用Actions的基本工作流

name: 自动部署

# 控制工作流何时运行
on:
  # 在推事件上触发工作流，但只针对主分支
  push:
    branches: [ master ]

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由一个或多个作业组成，这些作业可以按顺序或并行运行
jobs:
  # 该工作流包含一个名为“构建”的作业。
  build:
    # 作业将在其上运行的运行程序的类型
    runs-on: ubuntu-latest

    # 步骤表示将作为作业的一部分执行的任务序列
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.HUANG }}
        BRANCH: master
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run update
